site_name: UBELIX OnDemand Documentation

# Copyright footer
copyright: 'Copyright &copy; University of Bern, IT Service Office'
# Link to repo
repo_name: 'hpc-unibe-ch/hpc-docs'
repo_url: 'https://github.com/hpc-unibe-ch/hpc-unibe-ch.github.io'
edit_uri: 'edit/main/docs'

# Configuration
theme:
  name: material

extra_css:
  - 'stylesheets/unibe.css'

plugins:
  - git-revision-date
  - search

# See https://python-markdown.github.io/extensions/ and
# See https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions#Bundles
#     https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - sane_lists
  - smarty
  - tables
  - toc

# Social links bottom right
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/hpc-unibe-ch
